USE [master];
GO

-- Crear la base de datos 'zurich_db' sin rutas fijas
CREATE DATABASE [zurich_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'zurich_db', SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'zurich_db_log', SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF;
GO

-- Habilitar búsqueda de texto completo
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [zurich_db].[dbo].[sp_fulltext_database] @action = 'enable';
END;
GO

-- Configuraciones avanzadas de la base de datos
ALTER DATABASE [zurich_db] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [zurich_db] SET ANSI_NULLS OFF;
ALTER DATABASE [zurich_db] SET ANSI_PADDING OFF;
ALTER DATABASE [zurich_db] SET ANSI_WARNINGS OFF;
ALTER DATABASE [zurich_db] SET ARITHABORT OFF;
ALTER DATABASE [zurich_db] SET AUTO_CLOSE OFF;
ALTER DATABASE [zurich_db] SET AUTO_SHRINK OFF;
ALTER DATABASE [zurich_db] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [zurich_db] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [zurich_db] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [zurich_db] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [zurich_db] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [zurich_db] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [zurich_db] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [zurich_db] SET ENABLE_BROKER;
ALTER DATABASE [zurich_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF;
ALTER DATABASE [zurich_db] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [zurich_db] SET TRUSTWORTHY OFF;
ALTER DATABASE [zurich_db] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [zurich_db] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [zurich_db] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [zurich_db] SET HONOR_BROKER_PRIORITY OFF;
ALTER DATABASE [zurich_db] SET RECOVERY FULL;
ALTER DATABASE [zurich_db] SET MULTI_USER;
ALTER DATABASE [zurich_db] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [zurich_db] SET DB_CHAINING OFF;
ALTER DATABASE [zurich_db] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF);
ALTER DATABASE [zurich_db] SET TARGET_RECOVERY_TIME = 60 SECONDS;
ALTER DATABASE [zurich_db] SET DELAYED_DURABILITY = DISABLED;
ALTER DATABASE [zurich_db] SET ACCELERATED_DATABASE_RECOVERY = OFF;

-- Configuración del Query Store
ALTER DATABASE [zurich_db] SET QUERY_STORE = ON;
ALTER DATABASE [zurich_db] SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    INTERVAL_LENGTH_MINUTES = 60,
    MAX_STORAGE_SIZE_MB = 1000,
    QUERY_CAPTURE_MODE = AUTO,
    SIZE_BASED_CLEANUP_MODE = AUTO,
    MAX_PLANS_PER_QUERY = 200,
    WAIT_STATS_CAPTURE_MODE = ON
);

-- Habilitar escritura
ALTER DATABASE [zurich_db] SET READ_WRITE;
GO
