USE [zurich_db]
GO  

/****** Object:  Table [dbo].[RESGUARDO_BIO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESGUARDO_BIO](
	[ID_RESGUARDO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_RESGUARDO] [datetime2](0) NULL,
	[ID_EMPLEADO] [int] NULL,
	[ESTADO] [nvarchar](255) NULL,
	[ID_ACTIVO] [nvarchar](255) NULL,
	[ID_TECLADO] [nvarchar](255) NULL,
	[ID_MOUSE] [nvarchar](255) NULL,
	[ID_MONITOR] [nvarchar](255) NULL,
	[CARGADOR] [nvarchar](255) NULL,
	[MOUSE_PAD] [nvarchar](255) NULL,
	[USB] [nvarchar](255) NULL,
	[CABLE_HDMI] [nvarchar](255) NULL,
	[CABLE_VGA] [nvarchar](255) NULL,
	[ADAPTADOR_WIFI] [nvarchar](255) NULL,
	[NO_BREAK] [nvarchar](255) NULL,
	[TIPO_CARGADOR] [nvarchar](255) NULL,
	[ID_NOBREAK] [nvarchar](255) NULL,
	[OBJETIVO_POLITICAS] [nvarchar](50) NULL,
	[OBSERVACIONES_RESGUARDO] [nvarchar](max) NULL,
	[DOC_RESG_SCAN] [varchar](8000) NULL,
	[ID_CUENTA] [nvarchar](255) NULL,
 CONSTRAINT [RESGUARDO_BIO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_RESGUARDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO