USE [zurich_db]
GO  


/****** Object:  Table [dbo].[DEVOLUCION_EN_ARRENDAMIENTO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVOLUCION_EN_ARRENDAMIENTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_DEVOLUCION] [datetime2](0) NULL,
	[ID_ACTIVO] [nvarchar](255) NULL,
	[ELIMINADOR] [nvarchar](255) NULL,
	[ID_TECLADO] [nvarchar](255) NULL,
	[ID_MOUSE] [nvarchar](255) NULL,
	[MOTIVO_DEVOLUCION] [nvarchar](max) NULL,
	[CONDICIONES_ENTREGA] [nvarchar](max) NULL,
	[ELABORO] [int] NULL,
	[APROBO] [int] NULL,
	[RECIBIO] [int] NULL,
	[DOCUMENTOS] [varchar](8000) NULL,
 CONSTRAINT [DEVOLUCION_EN_ARRENDAMIENTO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO