USE [zurich_db]
GO  

/****** Object:  Table [dbo].[REPROGRAMACION]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPROGRAMACION](
	[ID_REPROGRAMACION] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_SOLICITUD] [datetime2](0) NULL,
	[FECHA_A_REPROGRAMAR] [datetime2](0) NULL,
	[FOLIO_RESGUARDO] [int] NULL,
	[MOTIVO] [nvarchar](max) NULL,
	[POLITICA] [int] NULL,
	[REALIZA] [int] NULL,
	[VERIFICA] [int] NULL,
	[AUTORIZA] [int] NULL,
	[DOCUMENTO] [varchar](8000) NULL,
 CONSTRAINT [REPROGRAMACION$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_REPROGRAMACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO