USE [zurich_db]
GO  

/****** Object:  Table [dbo].[CONTADOR_IMPRESION]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTADOR_IMPRESION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_IMPRESORA] [nvarchar](255) NULL,
	[FECHA] [datetime2](0) NULL,
	[TOTAL_IMP_COLOR] [nvarchar](255) NULL,
	[TOTAL_IMP_B/N] [nvarchar](255) NULL,
	[TOTAL_COPIAS_B/N] [nvarchar](255) NULL,
	[TOTAL_COPIAS_COLOR] [nvarchar](255) NULL,
 CONSTRAINT [CONTADOR_IMPRESION$ID1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO