USE [zurich_db]
GO  

/****** Object:  Table [dbo].[REPORTE_EXTRAVIO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORTE_EXTRAVIO](
	[ID_REPORTE] [int] IDENTITY(1,1) NOT NULL,
	[ID_COLABORADOR] [int] NULL,
	[FECHA DE EMISION] [datetime2](0) NULL,
	[FOLIO DE RESPONSIVA] [int] NULL,
	[OBSERVACION DE ACTONTECIMIENTO] [nvarchar](max) NULL,
	[FECHA COBERTURA] [datetime2](0) NULL,
	[MONTO A PAGAR] [money] NULL,
	[DETALLES DEL PAGO] [nvarchar](255) NULL,
	[EVIDENCIA FOTOGRAFICA] [varchar](8000) NULL,
	[ELABORO] [int] NULL,
	[VERIFICO] [int] NULL,
	[APROBO] [int] NULL,
	[VERIFICO02] [int] NULL,
	[ACEPTO] [int] NULL,
	[POLITICA] [int] NULL,
	[DOCUMENTO] [varchar](8000) NULL,
 CONSTRAINT [REPORTE_EXTRAVIO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_REPORTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO