USE [zurich_db]
GO  

/****** Object:  Table [dbo].[DEPARTAMENTOS_IMPRESORAS]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTOS_IMPRESORAS](
	[CLAVE_DEPARTAMENTO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION_DEPARTAMENTO] [nvarchar](255) NULL,
	[PIN_DEPARTAMENTO] [nvarchar](255) NULL,
	[TIPO_IMPRESION] [nvarchar](255) NULL,
 CONSTRAINT [DEPARTAMENTOS_IMPRESORAS$CLAVE_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[CLAVE_DEPARTAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO