USE [zurich_db]
GO  


/****** Object:  Table [dbo].[DEVOLUCION_PH]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVOLUCION_PH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_RESGUARDO] [int] NULL,
	[MOTIVO_DEV] [nvarchar](max) NULL,
	[CONDICIONES_ENTREGA] [nvarchar](max) NULL,
	[DOC_DEV_SCAN] [varchar](8000) NULL,
	[FECHA_DEV] [datetime2](0) NULL,
 CONSTRAINT [DEVOLUCION_PH$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

