USE [zurich_db]
GO

/****** Object:  Table [dbo].[SUCURSAL]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUCURSAL](
	[ID_SUCURSAL] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
 CONSTRAINT [SUCURSAL$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_SUCURSAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO