USE [zurich_db]
GO  

/****** Object:  Table [dbo].[CONSUMIBLES]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSUMIBLES](
	[ID_CONSUMIBLE] [int] IDENTITY(1,1) NOT NULL,
	[PERSONAL_TIS] [int] NOT NULL,
	[EMPLEADO] [nvarchar](255) NULL,
	[DESCRIPCION] [int] NOT NULL,
	[FECHA] [datetime2](0) NULL,
	[TIPO_MOVIMIENTO] [nvarchar](255) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
 CONSTRAINT [CONSUMIBLES$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_CONSUMIBLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO