USE [zurich_db]
GO  

/****** Object:  Table [dbo].[MANTENIMIENTO_BIO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANTENIMIENTO_BIO](
    [ID_MANTENIMIENTO] [int] IDENTITY(1,1) NOT NULL,
    [ID_ACTIVO] [nvarchar](255) NULL,
    [ID_EMPLEADO] [int] NULL,
    [FECHA_INICIO] [datetime2](0) NULL,
    [HORA_INICIO] [datetime2](0) NULL,
    [FECHA_FIN] [datetime2](0) NULL,
    [HORA_FIN] [datetime2](0) NULL,
    [OBSERVACIONES] [nvarchar](max) NULL,
    [DESCRIPCION] [nvarchar](max) NULL,
    [DOCUMENTO_ESCANEADO] [varchar](8000) NULL,
    [TIPO_MANTENIMIENTO] [nvarchar](255) NULL,
    [FECHA_PROXIMO_MANTENIMIENTO] [datetime2](0) NULL,
 CONSTRAINT [MANTENIMIENTO_BIO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
    [ID_MANTENIMIENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


