USE [zurich_db]
GO  

/****** Object:  Table [dbo].[OFFICE]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OFFICE](
    [ID_OFFICE] [int] IDENTITY(1,1) NOT NULL,
    [CLAVE_PRODUCTO] [nvarchar](255) NULL,
    [VERSION] [nvarchar](255) NULL,
    [CUENTA_ACT] [int] NULL,
    [ID_ACTIVO] [int] NULL,
    [FECHA_EXPIRACION] [datetime2](0) NULL,
    [OBSERVACIONES] [nvarchar](max) NULL,
    [FACTURA] [varchar](8000) NULL,
 CONSTRAINT [OFFICE$PrimaryKey] PRIMARY KEY CLUSTERED 
(
    [ID_OFFICE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO