USE [zurich_db]
GO

/****** Object:  Table [dbo].[ACTIVE_DIRECTORY_PHARMA_PH]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVE_DIRECTORY_PH](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_EMPLEADO] [float] NULL,
	[USUARIO] [nvarchar](255) NOT NULL,
	[CONTRASENA] [nvarchar](255) NOT NULL,
	[TIPO_USUARIO] [nvarchar](255) NULL,
	[SERVIDOR] [nvarchar](255) NULL,
	[DOMINIO] [nvarchar](255) NULL,
	[REMOTO] [nvarchar](255) NULL,
	[SAE] [nvarchar](255) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[GRUPO1] [nvarchar](255) NULL,
	[GRUPO2] [nvarchar](255) NULL,
	[GRUPO3] [nvarchar](255) NULL,
	[GRUPO4] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
	[GRUPO5] [nvarchar](255) NULL,
	[GRUPO6] [nvarchar](255) NULL,
	[GRUPO_SEG1] [nvarchar](255) NULL,
	[GRUPO_SEG2] [nvarchar](255) NULL,
 CONSTRAINT [ACTIVE_DIRECTORY_PHARMA_PH$ID1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
