USE [zurich_db]
GO  

/****** Object:  Table [dbo].[REPORTE_MOVIMIENTO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORTE_MOVIMIENTO](
	[ID_REPORTE] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime2](0) NULL,
	[ORIGEN] [nvarchar](max) NULL,
	[DESTINO] [nvarchar](max) NULL,
	[ID_ACTIVO] [nvarchar](255) NULL,
	[DETALLES MOVIMIENTO] [nvarchar](max) NULL,
	[ASIGNACION] [nvarchar](255) NULL,
	[BAJA] [nvarchar](255) NULL,
	[STOCK] [nvarchar](255) NULL,
	[ENVIO] [int] NULL,
	[TRANSPORTE] [int] NULL,
	[RECIBIO] [int] NULL,
 CONSTRAINT [REPORTE_MOVIMIENTO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_REPORTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO