USE [zurich_db]
GO


/****** Object:  Table [dbo].[IMPRESORA]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPRESORA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [nvarchar](255) NULL,
	[CONTRASENA] [nvarchar](255) NULL,
	[BLANCO_NEGRO] [nvarchar](255) NULL,
	[COLOR] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
	[ID_ACTIVO] [nvarchar](255) NULL,
	[ID_ACTIVO2] [nvarchar](255) NULL,
	[ID_ACTIVO3] [nvarchar](255) NULL,
	[ID_ACTIVO4] [nvarchar](255) NULL,
	[ID_ACTIVO5] [nvarchar](255) NULL,
	[ID_ACTIVO6] [nvarchar](255) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO2] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO3] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO4] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO5] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO6] [nvarchar](255) NULL,
 CONSTRAINT [IMPRESORA$ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO