USE [zurich_db]
GO


/****** Object:  Table [dbo].[CORREOS]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORREOS](
	[ID_CORREO] [int] IDENTITY(1,1) NOT NULL,
	[ID_EMPLEADO] [float] NULL,
	[ESTADO] [nvarchar](255) NULL,
	[DOMINIO] [nvarchar](255) NULL,
	[USUARIO] [nvarchar](255) NOT NULL,
	[CONTRASENA] [nvarchar](255) NOT NULL,
	[SOLO_CONSULTA] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
	[UBICACION] [nvarchar](255) NULL,
	[FECHA_CAMBIO_ESTADO] [datetime2](0) NULL,
 CONSTRAINT [CORREOS$ID] PRIMARY KEY CLUSTERED 
(
	[ID_CORREO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO