USE [zurich_db]
GO

/****** Object:  Table [dbo].[SOFTWARE]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE](
	[ID_SOFTWARE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
	[VERSION] [nvarchar](255) NULL,
	[LICENCIA] [nvarchar](255) NULL,
	[CUENTA_ADMIN] [nvarchar](255) NULL,
	[FECHA_ACTIVACION] [datetime2](0) NULL,
	[FECHA_EXPIRACION] [datetime2](0) NULL,
	[FACTURA] [varchar](8000) NULL,
	[DOCUMENTOS_RELACIONADOS] [varchar](8000) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
 CONSTRAINT [SOFTWARE$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_SOFTWARE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO