USE [zurich_db]
GO  

/****** Object:  Table [dbo].[SAE]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAE](
	[ID_CUENTA] [int] IDENTITY(1,1) NOT NULL,
	[ID_EMPLEADO] [int] NULL,
	[ESTADO] [nvarchar](255) NULL,
	[RAZON_SOCIAL] [nvarchar](255) NULL,
	[USUARIO] [nvarchar](255) NULL,
	[CONTRASENA] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](max) NULL,
 CONSTRAINT [SAE$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_CUENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO