USE [zurich_db]
GO

/****** Object:  Table [dbo].[DEPARTAMENTOS]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTAMENTOS](
	[ID_DEPARTAMENTO] [float] NOT NULL,
	[DESCRIPCION_CORTA] [nvarchar](255) NULL,
	[DESCRIPCION_DEPARTAMENTO] [nvarchar](255) NULL,
	[JEFE_RESPONSABLE] [nvarchar](255) NULL,
	[JERARQUIA] [nvarchar](255) NULL,
	[DEPENDE_DE_CLAVE] [nvarchar](255) NULL,
	[DEPENDE_DE] [nvarchar](255) NULL,
	[CUENTA_CONTABLE] [nvarchar](255) NULL,
	[PIN_IMPRESORA_B/N] [nvarchar](255) NULL,
	[ID_DEPARTAMENTO_COLOR] [nvarchar](255) NULL,
	[PIN_IMPRESORA_COLOR] [nvarchar](255) NULL,
 CONSTRAINT [DEPARTAMENTOS$CLAVE_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

