USE [zurich_db]
GO

/****** Object:  Table [dbo].[EMPLEADOS]    Script Date: 24/07/2025 02:09:35 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLEADOS](
	[ID_EMPLEADO] [int] NOT NULL,
	[NUM_OFICIAL] [int] NOT NULL,
	[NUM_PROVICIONAL] [int] NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[APELLIDO_PATERNO] [nvarchar](255) NULL,
	[APELLIDO_MATERNO] [nvarchar](255) NULL,
	[NOMBRE_COMPLETO] [nvarchar](255) NULL,
	[SEXO] [nvarchar](50) NULL,
	[ESTADO] [nvarchar](50) NOT NULL,
	[FECHA_ALTA] [date] NULL,
	[USUARIO_ULTIMA_MODIFICACION] [nvarchar](255) NULL,
	[FECHA_CONTRATACION] [date] NULL,
	[FECHA_BAJA] [date] NULL,
	[DEPARTAMENTO] [nvarchar](255) NULL,
	[PUESTO] [nvarchar](255) NULL,
	[CENTRO_COSTO] [nvarchar](255) NULL,
	[SUCURSAL] [nvarchar](255) NULL,
	[PLAN] [nvarchar](255) NULL,
	[TELEFONO_TRABAJO] [nvarchar](50) NULL,
	[TELEFONO_CELULAR] [nvarchar](50) NULL,
	[TELEFONO_OTRO] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[HORARIO_COMEDOR] [nvarchar](255) NULL,
	[TURNO] [nvarchar](255) NULL,
	[FOTO] [nvarchar](255) NULL,
	[JEFE_INMEDIATO] [nvarchar](255) NULL,
 CONSTRAINT [EMPLEADOS$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_NUM_OFICIAL] UNIQUE NONCLUSTERED 
(
	[NUM_OFICIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_NUM_PROVICIONAL] UNIQUE NONCLUSTERED 
(
	[NUM_PROVICIONAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

