USE [zurich_db]
GO


/****** Object:  Table [dbo].[PUESTOS]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUESTOS](
	[ID_PUESTO] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTAMENTO] [nvarchar](255) NOT NULL,
	[DESCRIPCION_PUESTO] [nvarchar](255) NULL,
	[JEFE_INMEDIATO] [nvarchar](255) NOT NULL,
	[SALARIO] [nvarchar](255) NULL,
	[CANTIDAD_VACANTES] [nvarchar](255) NOT NULL,
	[EMPRESA] [nvarchar](255) NULL,
 CONSTRAINT [PUESTOS$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_PUESTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO