USE [zurich_db]
GO


/****** Object:  Table [dbo].[SALIDA_Y_RETORNO_EQUIPO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALIDA_Y_RETORNO_EQUIPO](
	[ID_RETORNO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime2](0) NULL,
	[FOLIO_RESGUARDO] [float] NULL,
	[TIEMPO_QUE_SALDRA] [float] NULL,
	[UNIDAD_TIEMPO] [nvarchar](255) NULL,
	[MOTIVO_SALIDA] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
	[DOCUMENTOS] [nvarchar](255) NULL,
	[SOLICITANTE] [float] NULL,
	[AUTORIZA] [float] NULL,
	[VERIFICA01] [float] NULL,
	[VERIFICA02] [float] NULL,
	[VERIFICA03] [float] NULL,
 CONSTRAINT [SALIDA_Y_RETORNO_EQUIPO$ID1] PRIMARY KEY CLUSTERED 
(
	[ID_RETORNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO