USE [zurich_db]     
GO

/****** Object:  Table [dbo].[BAJA_EQUIPO]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAJA_EQUIPO](
	[ID_BAJA] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_BAJA] [datetime2](0) NOT NULL,
	[ID_ACTIVO] [nvarchar](255) NOT NULL,
	[MOTIVO_BAJA] [nvarchar](max) NULL,
	[HALLAZGO] [nvarchar](max) NULL,
	[EVIDENCIA FOTOGRAFICA] [varchar](8000) NULL,
	[DOCUMENTO] [varchar](8000) NULL,
	[ELABORO] [nvarchar](255) NULL,
	[APROBO] [nvarchar](255) NULL,
	[RECIBIO] [nvarchar](255) NULL,
 CONSTRAINT [BAJA_EQUIPO$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_BAJA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
