USE [zurich_db]
GO

/****** Object:  Table [dbo].[ANTIVIRUS]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANTIVIRUS](
	[ID_PRODUCTO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](255) NULL,
	[NUM_CUENTAS_PERMITIDAS] [int] NULL,
	[FECHA_ACT] [datetime2](0) NULL,
	[CORREO_ADMIN] [nvarchar](255) NULL,
	[FECHA_EXPIRACION] [datetime2](0) NULL,
	[CUENTAS_VINCULADAS] [nvarchar](max) NULL,
	[OBSERVACIONES] [nvarchar](max) NULL,
	[RAZON_SOCIAL] [nvarchar](255) NULL,
	[FACTURA] [varchar](8000) NULL,
	[VERSION] [nvarchar](max) NULL,
 CONSTRAINT [ANTIVIRUS$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO