USE [zurich_db]
GO

/****** Object:  Table [dbo].[INCIDENCIA]    Script Date: 03/07/2025 05:40:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INCIDENCIA](
	[ID_INCIDENCIA] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime2](0) NULL,
	[FECHA_PRESTAMO] [datetime2](0) NULL,
	[FECHA_ENTREGA] [datetime2](0) NULL,
	[ID_COLABORADOR] [int] NULL,
	[DESCRIPCION_ACTIVO] [nvarchar](max) NULL,
	[ID_ACTIVO] [nvarchar](255) NULL,
	[DESCRIPCION_INCIDENCIAS] [nvarchar](max) NULL,
	[ELABORO] [int] NULL,
	[VERIFICO] [int] NULL,
	[ACEPTO] [int] NULL,
	[DOCUMENTO] [varchar](8000) NULL,
 CONSTRAINT [INCIDENCIA$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[ID_INCIDENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO