# Generated by Django 5.0.14 on 2025-07-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('num_oficial', models.IntegerField(unique=True)),
                ('num_provicional', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('puesto', models.CharField(blank=True, max_length=255, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=255, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_otro', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_comedor', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
                ('jefe_inmediato', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EMPLEADOS',
                'managed': False,
            },
        ),
    ]
