# Generated by Django 5.0.14 on 2025-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQUIPOS',
            fields=[
                ('ID_EQUIPO', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=20)),
                ('RAZON_SOCIAL', models.CharField(max_length=100)),
                ('UBICACION', models.CharField(blank=True, max_length=100, null=True)),
                ('TIPO_EQUIPO', models.CharField(blank=True, max_length=50, null=True)),
                ('SITUACION', models.CharField(blank=True, max_length=50, null=True)),
                ('PROVEEDOR', models.CharField(blank=True, max_length=100, null=True)),
                ('MARCA', models.CharField(blank=True, max_length=50, null=True)),
                ('MODELO', models.CharField(blank=True, max_length=50, null=True)),
                ('SERIE', models.CharField(blank=True, max_length=50, null=True)),
                ('LINEA_TEL', models.CharField(blank=True, max_length=20, null=True)),
                ('IMEI', models.CharField(blank=True, max_length=20, null=True)),
                ('COMPANIA', models.CharField(blank=True, max_length=50, null=True)),
                ('PROCESADOR', models.CharField(blank=True, max_length=50, null=True)),
                ('RAM_1', models.CharField(blank=True, max_length=20, null=True)),
                ('RAM_2', models.CharField(blank=True, max_length=20, null=True)),
                ('DISCO_1', models.CharField(blank=True, max_length=20, null=True)),
                ('DISCO_2', models.CharField(blank=True, max_length=20, null=True)),
                ('SISTEMA_OPERATIVO', models.CharField(blank=True, max_length=50, null=True)),
                ('OBSERVATIONS', models.TextField(blank=True, null=True)),
                ('MAC_WIFI1', models.CharField(blank=True, max_length=17, null=True)),
                ('MAC_WIFI2', models.CharField(blank=True, max_length=17, null=True)),
                ('MAC_ETHERNET1', models.CharField(blank=True, max_length=17, null=True)),
                ('MAC_ETHERNET2', models.CharField(blank=True, max_length=17, null=True)),
                ('DEPARTAMENTO_ASIGNADO', models.CharField(blank=True, max_length=50, null=True)),
                ('FECHA_ALTA', models.DateTimeField(blank=True, null=True)),
                ('FOTO', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('DOCUMENTOS', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('ANTIVIRUS', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'EQUIPOS',
            },
        ),
        migrations.CreateModel(
            name='MONITORES',
            fields=[
                ('ID_MONITOR', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=20)),
                ('RAZON_SOCIAL', models.CharField(max_length=100)),
                ('MARCA', models.CharField(blank=True, max_length=50, null=True)),
                ('MODELO', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_SERIE', models.CharField(blank=True, max_length=50, null=True)),
                ('OBSERVATIONS', models.TextField(blank=True, null=True)),
                ('DOCUMENTOS', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'db_table': 'MONITORES',
            },
        ),
        migrations.CreateModel(
            name='NO_BREAKS',
            fields=[
                ('ID_BREAK', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=20)),
                ('RAZON_SOCIAL', models.CharField(max_length=100)),
                ('MARCA', models.CharField(blank=True, max_length=50, null=True)),
                ('MODELO', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_SERIE', models.CharField(blank=True, max_length=50, null=True)),
                ('OBSERVATIONS', models.TextField(blank=True, null=True)),
                ('DOCUMENTOS', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'db_table': 'NO_BREAKS',
            },
        ),
    ]
